# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Comeco.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_Tela_base(object):
    def setupUi(self, MainWindow_Tela_base):
        MainWindow_Tela_base.setObjectName("MainWindow_Tela_base")
        MainWindow_Tela_base.resize(1072, 834)
        MainWindow_Tela_base.setMinimumSize(QtCore.QSize(500, 700))
        MainWindow_Tela_base.setStyleSheet("background-color: rgb(42, 42, 42);")
        self.centralwidget_Tela_base = QtWidgets.QWidget(MainWindow_Tela_base)
        self.centralwidget_Tela_base.setObjectName("centralwidget_Tela_base")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget_Tela_base)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.conteudo_Tela_base = QtWidgets.QFrame(self.centralwidget_Tela_base)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.conteudo_Tela_base.setFont(font)
        self.conteudo_Tela_base.setStyleSheet("background-color: rgb(42, 42, 42);")
        self.conteudo_Tela_base.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.conteudo_Tela_base.setFrameShadow(QtWidgets.QFrame.Raised)
        self.conteudo_Tela_base.setObjectName("conteudo_Tela_base")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.conteudo_Tela_base)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Tela_Base = QtWidgets.QFrame(self.conteudo_Tela_base)
        self.Tela_Base.setMaximumSize(QtCore.QSize(1000, 1000))
        self.Tela_Base.setStyleSheet("background-color: rgb(60, 60, 60);\n"
"border-radius: 10px;")
        self.Tela_Base.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Tela_Base.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Tela_Base.setObjectName("Tela_Base")
        self.label = QtWidgets.QLabel(self.Tela_Base)
        self.label.setGeometry(QtCore.QRect(30, 20, 591, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 60, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 60, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 60, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 60, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 60, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 60, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 60, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 60, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 60, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.Tela_Base)
        self.label_2.setGeometry(QtCore.QRect(40, 90, 161, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 60, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 60, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 60, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 60, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 60, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 60, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 60, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 60, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 60, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_2.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.tabWidget = QtWidgets.QTabWidget(self.Tela_Base)
        self.tabWidget.setGeometry(QtCore.QRect(40, 160, 921, 631))
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setObjectName("tab1")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.tab1)
        self.textBrowser_3.setGeometry(QtCore.QRect(0, -10, 921, 641))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(40)
        font.setBold(False)
        font.setWeight(50)
        self.textBrowser_3.setFont(font)
        self.textBrowser_3.setStyleSheet("background-color: white;\n"
"padding-left: 20px; padding-right: 40px; padding-top: 40 px; padding-bottom: 20px;\n"
"font-size: 40pt")
        self.textBrowser_3.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.tabWidget.addTab(self.tab1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.tab_2)
        self.textBrowser_2.setGeometry(QtCore.QRect(0, -10, 921, 641))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(40)
        font.setBold(False)
        font.setWeight(50)
        self.textBrowser_2.setFont(font)
        self.textBrowser_2.setStyleSheet("background-color: white;\n"
"padding-left: 20px; padding-right: 40px; padding-top: 40 px; padding-bottom: 20px;\n"
"font-size: 40pt")
        self.textBrowser_2.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.tab_3)
        self.textBrowser_4.setGeometry(QtCore.QRect(0, -10, 921, 641))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(40)
        font.setBold(False)
        font.setWeight(50)
        self.textBrowser_4.setFont(font)
        self.textBrowser_4.setStyleSheet("background-color: white;\n"
"padding-left: 20px; padding-right: 40px; padding-top: 40 px; padding-bottom: 20px;\n"
"font-size: 40pt")
        self.textBrowser_4.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.textBrowser_5 = QtWidgets.QTextBrowser(self.tab)
        self.textBrowser_5.setGeometry(QtCore.QRect(0, -10, 921, 641))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(40)
        font.setBold(False)
        font.setWeight(50)
        self.textBrowser_5.setFont(font)
        self.textBrowser_5.setStyleSheet("background-color: white;\n"
"padding-left: 20px; padding-right: 40px; padding-top: 40 px; padding-bottom: 20px;\n"
"font-size: 40pt")
        self.textBrowser_5.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.tabWidget.addTab(self.tab, "")
        self.label_3 = QtWidgets.QLabel(self.Tela_Base)
        self.label_3.setGeometry(QtCore.QRect(600, 130, 371, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 60, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 60, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 60, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 60, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 60, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 60, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 60, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 60, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 60, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_3.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.Tela_Base)
        self.verticalLayout.addWidget(self.conteudo_Tela_base)
        MainWindow_Tela_base.setCentralWidget(self.centralwidget_Tela_base)

        self.retranslateUi(MainWindow_Tela_base)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_Tela_base)

    def retranslateUi(self, MainWindow_Tela_base):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_Tela_base.setWindowTitle(_translate("MainWindow_Tela_base", "Tela_base"))
        self.label.setText(_translate("MainWindow_Tela_base", "Como Começar a investir na Bolsa"))
        self.label_2.setText(_translate("MainWindow_Tela_base", "O Que Saber?"))
        self.textBrowser_3.setHtml(_translate("MainWindow_Tela_base", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:40pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt; vertical-align:super;\">A bolsa de valores é um espaço para compra e venda de ativos financeiros, no qual empresas buscam se capitalizar e investidores procuram negócios de rentabilidade mais atraente do que a renda fixa – e de maior risco. É nesse ambiente que companhias abrem seu capital e investidores compram e vendem papéis, de forma segura, transparente e organizada.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt; vertical-align:super;\">Ações não são os únicos produtos financeiros nesse mercado. Contratos de moeda estrangeira, derivativos e commodities são exemplos de papéis negociados na bolsa.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt; vertical-align:super;\">No Brasil, a empresa responsável pela bolsa de valores chama-se B3, e todas as negociações são regulamentadas pela Comissão de Valores Mobiliários.</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), _translate("MainWindow_Tela_base", "O que é a Bolsa de Valores?"))
        self.textBrowser_2.setHtml(_translate("MainWindow_Tela_base", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:40pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt; vertical-align:super;\">O imaginário criado em torno da bolsa de valores é de um grande salão com corretores engravatados gritando ordens de compra e venda. Isso ficou no passado, e atualmente a maioria das bolsas opera de forma on-line.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt; vertical-align:super;\">Podemos resumir o funcionamento da bolsa em:</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:1; text-indent:0px;\"><span style=\" font-size:28pt; vertical-align:super;\">Abertura de capital de empresa com oferta pública inicial, a chamada IPO</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:1; text-indent:0px;\"><span style=\" font-size:28pt; vertical-align:super;\">Transferência das ações, antes exclusivas da empresa, para a bolsa</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:1; text-indent:0px;\"><span style=\" font-size:28pt; vertical-align:super;\">Definição do preço das ações no mercado primário, onde ocorre a primeira negociação</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:1; text-indent:0px;\"><span style=\" font-size:28pt; vertical-align:super;\">Estabelecimento de oferta e demanda das ações</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:1; text-indent:0px;\"><span style=\" font-size:28pt; vertical-align:super;\">Compra e venda das ações entre investidores no mercado secundário</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt; vertical-align:super;\">Estão listadas na bolsa de valores brasileira cerca de 400 empresas, de setores que vão de bens industriais, consumo e saúde a combustíveis, tecnologia da informação e telecomunicações.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt; vertical-align:super;\">As ações mais negociadas compõem o Ibovespa, índice que monitora o desempenho da bolsa. Esse é o termômetro do mercado.</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow_Tela_base", "Como Funciona"))
        self.textBrowser_4.setHtml(_translate("MainWindow_Tela_base", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:40pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:14px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt; font-weight:600; vertical-align:super;\">Ações</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt; vertical-align:super;\">Ações são cotas de uma empresa. Quando você compra ações, torna-se sócio. É como se você fosse dono de um pedacinho da organização. Quanto mais ações tiver, maior será seu retorno sobre parte dos lucros ou quando vender os papéis na alta.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt; vertical-align:super;\">As ações podem ser ordinárias ou preferenciais. As primeiras são mais comuns e permitem ao investidor votar em eleições do conselho. As segundas dão prioridade no pagamento de dividendos.</span></p>\n"
"<p style=\" margin-top:14px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt; font-weight:600; vertical-align:super;\">Home Broker</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt; vertical-align:super;\">Home broker é a plataforma on-line disponibilizada pelas corretoras. Dessa forma, você pode operar na bolsa de onde estiver sem a necessidade de falar com um corretor.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt; vertical-align:super;\">Você compra e vende ações do seu computador ou celular. Mas fique atento ao horário de abertura e fechamento do mercado, que geralmente é das 10h às 17h.</span></p>\n"
"<p style=\" margin-top:14px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt; font-weight:600; vertical-align:super;\">Dividendos</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt; vertical-align:super;\">Dividendos são parcelas dos lucros das empresas que são distribuídas aos acionistas periodicamente. O valor muda conforme a quantidade de ações, o lucro e as estratégias da companhia.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt; vertical-align:super;\">O pagamento pode ser mensal, trimestral, semestral ou eventual, de acordo com a política de cada organização. O depósito em dinheiro é feito na sua conta da corretora de valores.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt; vertical-align:super;\">Um indicador importante é o dividend yield, valor do dividendo em relação ao preço pago pela ação. Quanto maior for o dividend yield, mais você vai receber em dividendos por cada papel comprado.</span></p>\n"
"<p style=\" margin-top:14px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt; font-weight:600; vertical-align:super;\">Circuit breaker</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt; vertical-align:super;\">Um mecanismo importante da bolsa de valores é o circuit breaker, que suspende as negociações temporariamente em caso de oscilações muito vigorosas. Serve para proteger os investidores em momentos de pânico do mercado.</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow_Tela_base", "Principais Termos Utilizados"))
        self.textBrowser_5.setHtml(_translate("MainWindow_Tela_base", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:40pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:14px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt; font-weight:600; vertical-align:super;\">Comece devagar</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt; vertical-align:super;\">Mesmo que você se identifique como um investidor moderado ou arrojado, vá com muita calma nas primeiras investidas na bolsa de valores. Até a hora em que você vê uma flutuação negativa de 50% na sua carteira, não tem ideia do que significa risco e volatilidade.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt; vertical-align:super;\">Por isso, imagine que todo o investimento na bolsa pode sofrer uma retração de 50%, mesmo que momentaneamente. Você está preparado para isso? Então comece com 5% ou 10% do seu capital, para aos poucos sentir o mercado, aprender e prosperar.</span></p>\n"
"<p style=\" margin-top:14px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt; font-weight:600; vertical-align:super;\">Entenda o ativo no qual você investe</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt; vertical-align:super;\">Estude as empresas que você considera para a sua carteira. Informe-se sobre a saúde financeira, pesquise o desempenho desses papéis, entenda se o preço da ação está de acordo com o valor patrimonial e o fluxo de caixa futuro e analise os concorrentes.</span></p>\n"
"<p style=\" margin-top:14px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt; font-weight:600; vertical-align:super;\">Acompanhe as notícias</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt; vertical-align:super;\">Além de conhecer a fundo as empresas das quais você será acionista, é preciso acompanhar notícias do mercado financeiro e de setores que impactam a bolsa. Política, eleições, relações internacionais, economia, tanto no Brasil quanto em outros países, são variáveis a serem observadas.</span></p>\n"
"<p style=\" margin-top:14px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt; font-weight:600; vertical-align:super;\">Planeje suas finanças</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt; vertical-align:super;\">O planejamento financeiro é outro ponto fundamental. Defina quanto está disposto a investir e por quanto tempo –lembrando sempre que a bolsa de valores é investimento de longo prazo, superior a cinco anos. Então, nunca invista todo o seu patrimônio e mantenha sempre uma reserva de emergência, com ativos líquidos e seguros.</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow_Tela_base", "Primeiros Passos"))
        self.label_3.setText(_translate("MainWindow_Tela_base", "Fonte: https://www.onze.com.br/blog/bolsa-de-valores-principiantes/"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow_Tela_base = QtWidgets.QMainWindow()
    ui = Ui_MainWindow_Tela_base()
    ui.setupUi(MainWindow_Tela_base)
    MainWindow_Tela_base.show()
    sys.exit(app.exec_())
