# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Tesouro.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_Tela_base(object):
    def setupUi(self, MainWindow_Tela_base):
        MainWindow_Tela_base.setObjectName("MainWindow_Tela_base")
        MainWindow_Tela_base.resize(1072, 834)
        MainWindow_Tela_base.setMinimumSize(QtCore.QSize(500, 700))
        MainWindow_Tela_base.setStyleSheet("background-color: rgb(42, 42, 42);")
        self.centralwidget_Tela_base = QtWidgets.QWidget(MainWindow_Tela_base)
        self.centralwidget_Tela_base.setObjectName("centralwidget_Tela_base")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget_Tela_base)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.conteudo_Tela_base = QtWidgets.QFrame(self.centralwidget_Tela_base)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.conteudo_Tela_base.setFont(font)
        self.conteudo_Tela_base.setStyleSheet("background-color: rgb(42, 42, 42);")
        self.conteudo_Tela_base.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.conteudo_Tela_base.setFrameShadow(QtWidgets.QFrame.Raised)
        self.conteudo_Tela_base.setObjectName("conteudo_Tela_base")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.conteudo_Tela_base)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Tela_Base = QtWidgets.QFrame(self.conteudo_Tela_base)
        self.Tela_Base.setMaximumSize(QtCore.QSize(1000, 1000))
        self.Tela_Base.setStyleSheet("background-color: rgb(60, 60, 60);\n"
"border-radius: 10px;")
        self.Tela_Base.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Tela_Base.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Tela_Base.setObjectName("Tela_Base")
        self.label = QtWidgets.QLabel(self.Tela_Base)
        self.label.setGeometry(QtCore.QRect(30, 20, 591, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 60, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 60, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 60, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 60, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 60, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 60, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 60, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 60, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 60, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.Tela_Base)
        self.label_2.setGeometry(QtCore.QRect(40, 90, 161, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 60, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 60, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 60, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 60, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 60, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 60, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 60, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 60, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 60, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_2.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.tabWidget = QtWidgets.QTabWidget(self.Tela_Base)
        self.tabWidget.setGeometry(QtCore.QRect(40, 160, 921, 631))
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setObjectName("tab1")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.tab1)
        self.textBrowser_3.setGeometry(QtCore.QRect(0, -10, 921, 641))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(40)
        font.setBold(False)
        font.setWeight(50)
        self.textBrowser_3.setFont(font)
        self.textBrowser_3.setStyleSheet("background-color: white;\n"
"padding-left: 20px; padding-right: 40px; padding-top: 40 px; padding-bottom: 20px;\n"
"font-size: 40pt")
        self.textBrowser_3.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.tabWidget.addTab(self.tab1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.tab_2)
        self.textBrowser_2.setGeometry(QtCore.QRect(0, -10, 921, 641))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(40)
        font.setBold(False)
        font.setWeight(50)
        self.textBrowser_2.setFont(font)
        self.textBrowser_2.setStyleSheet("background-color: white;\n"
"padding-left: 20px; padding-right: 40px; padding-top: 40 px; padding-bottom: 20px;\n"
"font-size: 40pt")
        self.textBrowser_2.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.tab_3)
        self.textBrowser_4.setGeometry(QtCore.QRect(0, -10, 921, 641))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(40)
        font.setBold(False)
        font.setWeight(50)
        self.textBrowser_4.setFont(font)
        self.textBrowser_4.setStyleSheet("background-color: white;\n"
"padding-left: 20px; padding-right: 40px; padding-top: 40 px; padding-bottom: 20px;\n"
"font-size: 40pt")
        self.textBrowser_4.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.textBrowser_5 = QtWidgets.QTextBrowser(self.tab)
        self.textBrowser_5.setGeometry(QtCore.QRect(0, -10, 921, 641))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(40)
        font.setBold(False)
        font.setWeight(50)
        self.textBrowser_5.setFont(font)
        self.textBrowser_5.setStyleSheet("background-color: white;\n"
"padding-left: 20px; padding-right: 40px; padding-top: 40 px; padding-bottom: 20px;\n"
"font-size: 40pt")
        self.textBrowser_5.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.tabWidget.addTab(self.tab, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.textBrowser_6 = QtWidgets.QTextBrowser(self.tab_4)
        self.textBrowser_6.setGeometry(QtCore.QRect(0, -10, 921, 641))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(40)
        font.setBold(False)
        font.setWeight(50)
        self.textBrowser_6.setFont(font)
        self.textBrowser_6.setStyleSheet("background-color: white;\n"
"padding-left: 20px; padding-right: 40px; padding-top: 40 px; padding-bottom: 20px;\n"
"font-size: 40pt")
        self.textBrowser_6.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.textBrowser_6.setObjectName("textBrowser_6")
        self.tabWidget.addTab(self.tab_4, "")
        self.textBrowser = QtWidgets.QTextBrowser(self.Tela_Base)
        self.textBrowser.setGeometry(QtCore.QRect(710, 130, 251, 31))
        self.textBrowser.setObjectName("textBrowser")
        self.horizontalLayout.addWidget(self.Tela_Base)
        self.verticalLayout.addWidget(self.conteudo_Tela_base)
        MainWindow_Tela_base.setCentralWidget(self.centralwidget_Tela_base)

        self.retranslateUi(MainWindow_Tela_base)
        self.tabWidget.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_Tela_base)

    def retranslateUi(self, MainWindow_Tela_base):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_Tela_base.setWindowTitle(_translate("MainWindow_Tela_base", "Tela_base"))
        self.label.setText(_translate("MainWindow_Tela_base", "Tesouro Direto"))
        self.label_2.setText(_translate("MainWindow_Tela_base", "O Que Saber?"))
        self.textBrowser_3.setHtml(_translate("MainWindow_Tela_base", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:40pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt; vertical-align:super;\">É um programa de intermediação entre pessoas físicas e Governo Federal, onde é feita a negociação de títulos públicos entre as duas partes através da internet.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt; vertical-align:super;\">A grosso modo, pode-se considerar que, por meio do Tesouro Direto, o pequeno investidor tem a possibilidade de “emprestar” dinheiro, em troca de rentabilidade para esse capital, ao governo, que tem como objetivo arrecadar essas aplicações a fim de pagar e financiar muitas de suas atividades, como saúde, infraestrutura e educação, por exemplo.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt; vertical-align:super;\">Assim, como essa modalidade de aplicação se faz entre pessoa física e governo federal, seus riscos são baixíssimos quando comparado a outros tipos de investimentos ligados a instituições financeiras, empresas de capital aberto ou fundos de investimentos imobiliários.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt; vertical-align:super;\">Esse é um dos principais motivos que faz muitas pessoas se interessarem pelo Tesouro Direto, pois sua segurança e praticidade realmente transmite uma grande sensação de segurança ao investidor, principalmente os iniciantes.</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), _translate("MainWindow_Tela_base", "O Que Preciso saber para começar?"))
        self.textBrowser_2.setHtml(_translate("MainWindow_Tela_base", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:40pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt; vertical-align:super;\">Para o Tesouro Direto, é descontada a taxa de custódia, que é cobrada pela BMF&amp;Bovespa e corresponde a 0,30% ao ano (refere-se aos serviços de guarda dos títulos e às informações e movimentações dos saldos); e ainda as taxas cobradas pelas instituições financeiras, que podem ser de 0% a 2% ao ano, variando de instituição para instituição, independentemente do valor do seu investimento.</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow_Tela_base", "Custos"))
        self.textBrowser_4.setHtml(_translate("MainWindow_Tela_base", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:40pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:14px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt; font-weight:600; vertical-align:super;\">Títulos Prefixados</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt; vertical-align:super;\">Esse tipo de título apresenta uma taxa de rentabilidade já conhecida no momento de sua compra. Isso significa que, ao se adquirir um Título Prefixado, o investidor já fica ciente, no momento da aplicação, qual será a taxa de juros que receberá no final do período do investimento.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt; vertical-align:super;\">Normalmente, esses títulos são indicados para o investidor que acredita que a taxa prefixada será maior que a taxa de juros básica da economia (Selic).</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt; vertical-align:super;\">Ou seja, é aconselhável que se aplique nesse ativo quando a taxa de juros esteja alta, mas com possibilidade real de que ela recue no médio prazo.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt; vertical-align:super;\">Desta forma, o investidor mantém a rentabilidade com a Selic elevada e, mesmo que ela venha a cair depois, ele receberá o valor de rentabilidade acordado no início da operação, que nesse caso será maior ao final do prazo do investimento.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt; vertical-align:super;\">Dentro dos Prefixados existem dois ativos, o Tesouro Prefixado (LTN) e o Tesouro Prefixado com Juros Semestrais (NTN-F).</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:28pt; vertical-align:super;\"><br /></p>\n"
"<p style=\" margin-top:14px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt; font-weight:600; vertical-align:super;\">Títulos Pós-fixados</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt; vertical-align:super;\">A característica principal desse tipo de ativo está no fato desses títulos terem seu valor corrigido por um indexador, que normalmente é a taxa básica de juros (Selic) ou a inflação (IPCA).</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt; vertical-align:super;\">Assim, a rentabilidade da aplicação é composta por uma taxa pré-determinada no momento da compra do título pelo investidor e mais a variação de um indexador, ou seja, dessa forma, no momento da aplicação, não se sabe precisamente qual será o valor dos rendimentos ao final da aplicação.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt; vertical-align:super;\">Pode-se dizer, portanto, que os Títulos Pós-Fixados, apesar de serem muito seguros, apresentam o “risco” de o investidor conseguir, em alguns casos, menor rentabilidade do que o esperado no final da aplicação.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt; vertical-align:super;\">Os títulos disponíveis nessa modalidade são Tesouro IPCA+ (NTN-B Principal), Tesouro IPCA+ com Juros Semestrais (NTN-B) e Tesouro Selic (LFT), sendo os dois primeiros indexados à Inflação, e o último sendo indexado à Taxa Selic.</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow_Tela_base", "Tipos de Tesouro Direto"))
        self.textBrowser_5.setHtml(_translate("MainWindow_Tela_base", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:40pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt; vertical-align:super;\">O tesouro direto não é coberto pelo FGC, porém como é um título do governo, é um dos investimentos mais seguros do mercado.</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow_Tela_base", "Riscos"))
        self.textBrowser_6.setHtml(_translate("MainWindow_Tela_base", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:40pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt; vertical-align:super;\">Inserir texto</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow_Tela_base", "Mais Informações"))
        self.textBrowser.setHtml(_translate("MainWindow_Tela_base", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt; color:#ffffff;\">Fonte: https://www.sunoresearch.com.br/artigos/tesouro-direto-guia-explicativo-com-tabela-de-titulos</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow_Tela_base = QtWidgets.QMainWindow()
    ui = Ui_MainWindow_Tela_base()
    ui.setupUi(MainWindow_Tela_base)
    MainWindow_Tela_base.show()
    sys.exit(app.exec_())
